name: Python

on:
  [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.3"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
