name: Python

on:
  [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.3"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Pytest
        if: ${{ secrets.GEMINI_API_KEY }}
        env:
          GEMINI_API_KEY: GEMINI_API_KEY
        run: |
          python -m pytest

